src/maasserver/urls.py
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""URL routing configuration."""

from __future__ import (
    absolute_import,
    print_function,
    unicode_literals,
    )

__metaclass__ = type
__all__ = []


from django.conf.urls.defaults import (
    include,
    patterns,
    url,
    )
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.simple import (
    direct_to_template,
    redirect_to,
    )
from maasserver.models import Node
from maasserver.views.account import (
    login,
    logout,
    )
from maasserver.views.nodes import (
    enlist_preseed_view,
    MacAdd,
    MacDelete,
    NodeDelete,
    NodeEdit,
    NodeListView,
    NodePreseedView,
    NodeView,
    )
from maasserver.views.prefs import (
    SSHKeyCreateView,
    SSHKeyDeleteView,
    userprefsview,
    )
from maasserver.views.settings import (
    AccountsAdd,
    AccountsDelete,
    AccountsEdit,
    AccountsView,
    settings,
    settings_add_archive,
    )


def adminurl(regexp, view, *args, **kwargs):
    view = user_passes_test(lambda u: u.is_superuser)(view)
    return url(regexp, view, *args, **kwargs)


## URLs accessible to anonymous users.
# Combo URLs.
urlpatterns = patterns('',
    (r'combo/', include('maasserver.urls_combo'))
)

# Anonymous views.
urlpatterns += patterns('maasserver.views',
    url(r'^accounts/login/$', login, name='login'),
    url(
        r'^robots\.txt$', direct_to_template,
        {'template': 'maasserver/robots.txt', 'mimetype': 'text/plain'},
        name='robots'),
    url(
        r'^favicon\.ico$', redirect_to, {'url': '/static/img/favicon.ico'},
        name='favicon'),
)

## URLs for logged-in users.
# Preferences views.
urlpatterns += patterns('maasserver.views',
    url(r'^account/prefs/$', userprefsview, name='prefs'),
    url(
        r'^account/prefs/sshkey/add/$', SSHKeyCreateView.as_view(),
        name='prefs-add-sshkey'),
    url(
        r'^account/prefs/sshkey/delete/(?P<keyid>\d*)/$',
        SSHKeyDeleteView.as_view(), name='prefs-delete-sshkey'),
    )

# Logout view.
urlpatterns += patterns('maasserver.views',
    url(r'^accounts/logout/$', logout, name='logout'),
)

# Nodes views.
urlpatterns += patterns('maasserver.views',
    url(
        r'^$',
        NodeListView.as_view(template_name="maasserver/index.html"),
        name='index'),
    url(r'^nodes/$', NodeListView.as_view(model=Node), name='node-list'),
    url(r'^nodes/enlist-preseed/$', enlist_preseed_view,
        name='enlist-preseed-view'),
    url(
        r'^nodes/(?P<system_id>[\w\-]+)/view/$', NodeView.as_view(),
        name='node-view'),
    url(
        r'^nodes/(?P<system_id>[\w\-]+)/preseedview/$',
        NodePreseedView.as_view(), name='node-preseed-view'),
     url(
        r'^nodes/(?P<system_id>[\w\-]+)/edit/$', NodeEdit.as_view(),
        name='node-edit'),
    url(
        r'^nodes/(?P<system_id>[\w\-]+)/delete/$', NodeDelete.as_view(),
        name='node-delete'),
    url(
        r'^nodes/(?P<system_id>[\w\-]+)/macs/(?P<mac_address>.+)/delete/$',
        MacDelete.as_view(), name='mac-delete'),
    url(
        r'^nodes/(?P<system_id>[\w\-]+)/macs/add/$',
        MacAdd.as_view(), name='mac-add'),
)


## URLs for admin users.
# Settings views.
urlpatterns += patterns('maasserver.views',
    adminurl(r'^settings/$', settings, name='settings'),
    adminurl(
        r'^settings/archives/add/$', settings_add_archive,
        name='settings-add-archive'),
    adminurl(r'^accounts/add/$', AccountsAdd.as_view(), name='accounts-add'),
    adminurl(
        r'^accounts/(?P<username>\w+)/edit/$', AccountsEdit.as_view(),
        name='accounts-edit'),
    adminurl(
        r'^accounts/(?P<username>\w+)/view/$', AccountsView.as_view(),
        name='accounts-view'),
    adminurl(
        r'^accounts/(?P<username>\w+)/del/$', AccountsDelete.as_view(),
        name='accounts-del'),
)


# API URLs.
urlpatterns += patterns('',
    (r'^api/1\.0/', include('maasserver.urls_api'))
    )

src/maasserver/forms.py
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Forms."""

from __future__ import (
    absolute_import,
    print_function,
    unicode_literals,
    )

__metaclass__ = type
__all__ = [
    "AdminNodeWithMACAddressesForm",
    "CommissioningForm",
    "get_action_form",
    "get_node_edit_form",
    "get_node_create_form",
    "HostnameFormField",
    "MACAddressForm",
    "MAASAndNetworkForm",
    "NodeWithMACAddressesForm",
    "SSHKeyForm",
    "UbuntuForm",
    "AdminNodeForm",
    ]

from django import forms
from django.contrib import messages
from django.contrib.auth.forms import (
    UserChangeForm,
    UserCreationForm,
    )
from django.contrib.auth.models import (
    AnonymousUser,
    User,
    )
from django.core.exceptions import (
    PermissionDenied,
    ValidationError,
    )
from django.core.validators import URLValidator
from django.forms import (
    CharField,
    Form,
    ModelForm,
    )
from maasserver.config_forms import SKIP_CHECK_NAME
from maasserver.enum import (
    ARCHITECTURE,
    ARCHITECTURE_CHOICES,
    NODE_AFTER_COMMISSIONING_ACTION,
    NODE_AFTER_COMMISSIONING_ACTION_CHOICES,
    )
from maasserver.fields import MACAddressFormField
from maasserver.models import (
    Config,
    MACAddress,
    Node,
    NodeGroup,
    SSHKey,
    )
from maasserver.node_action import compile_node_actions
from maasserver.power_parameters import POWER_TYPE_PARAMETERS
from provisioningserver.enum import (
    POWER_TYPE,
    POWER_TYPE_CHOICES,
    )


def compose_invalid_choice_text(choice_of_what, valid_choices):
    """Compose an "invalid choice" string for form error messages.

    :param choice_of_what: The name for what the selected item is supposed
        to be, to be inserted into the error string.
    :type choice_of_what: basestring
    :param valid_choices: Valid choices, in Django choices format:
        (name, value).
    :type valid_choices: sequence
    """
    return "%s is not a valid %s.  It should be one of: %s." % (
        "%(value)s",
        choice_of_what,
        ", ".join(name for name, value in valid_choices),
        )


INVALID_ARCHITECTURE_MESSAGE = compose_invalid_choice_text(
    'architecture', ARCHITECTURE_CHOICES)


class NodeForm(ModelForm):
    after_commissioning_action = forms.TypedChoiceField(
        label="After commissioning",
        choices=NODE_AFTER_COMMISSIONING_ACTION_CHOICES, required=False,
        empty_value=NODE_AFTER_COMMISSIONING_ACTION.DEFAULT)

    architecture = forms.ChoiceField(
        choices=ARCHITECTURE_CHOICES, required=True,
        initial=ARCHITECTURE.i386,
        error_messages={'invalid_choice': INVALID_ARCHITECTURE_MESSAGE})

    class Meta:
        model = Node
        fields = (
            'hostname',
            'after_commissioning_action',
            'architecture',
            )


def remove_None_values(data):
    """Return a new dictionary without the keys corresponding to None values.
    """
    return {key: value for key, value in data.items() if value is not None}


class APIEditMixin:
    """A mixin that clears None values after the cleaning phase.

    Form data contain None values for missing fields.  This class
    removes these None values before processing the data.
    """

    def _post_clean(self):
        """Override Django's private hook _post_save to remove None values
        from 'self.cleaned_data'.

        _post_clean is where the fields of the instance get set with the data
        from self.cleaned_data.  That's why the cleanup needs to happen right
        before that.
        """
        self.cleaned_data = remove_None_values(self.cleaned_data)
        super(APIEditMixin, self)._post_clean()


class AdminNodeForm(APIEditMixin, NodeForm):
    """A version of NodeForm with adds the fields 'power_type' and
    'power_parameters'.
    """

    class Meta:
        model = Node
        fields = (
            'hostname',
            'after_commissioning_action',
            'architecture',
            'power_type',
            'power_parameters',
            )

    def __init__(self, data=None, files=None, instance=None, initial=None):
        super(AdminNodeForm, self).__init__(
            data=data, files=files, instance=instance, initial=initial)
        self.set_up_power_parameters_field(data, instance)

    def set_up_power_parameters_field(self, data, node):
        """Setup the 'power_parameter' field based on the value for the
        'power_type' field.

        We need to create the field for 'power_parameter' (which depend from
        the value of the field 'power_type') before the value for power_type
        gets validated.
        """
        if data is None:
            data = {}

        power_type = data.get('power_type', self.initial.get('power_type'))

        # If power_type is None (this is a node creation form or this
        # form deals with an API call which does not change the value of
        # 'power_type') or invalid: get the node's current 'power_type'
        # value or the default value if this form is not linked to a node.
        if power_type is None or power_type not in dict(POWER_TYPE_CHOICES):
            if node is not None:
                power_type = node.power_type
            else:
                power_type = POWER_TYPE.DEFAULT
        self.fields['power_parameters'] = (
            POWER_TYPE_PARAMETERS[power_type])

    def clean(self):
        cleaned_data = super(AdminNodeForm, self).clean()
        # If power_type is DEFAULT and power_parameters_skip_check is not
        # on, reset power_parameters (set it to the empty string).
        is_default = cleaned_data['power_type'] == POWER_TYPE.DEFAULT
        skip_check = (
            self.data.get('power_parameters_%s' % SKIP_CHECK_NAME) == 'true')
        if is_default and not skip_check:
            cleaned_data['power_parameters'] = ''
        return cleaned_data


def get_node_edit_form(user):
    if user.is_superuser:
        return AdminNodeForm
    else:
        return NodeForm


class MACAddressForm(ModelForm):
    class Meta:
        model = MACAddress

    def __init__(self, node, *args, **kwargs):
        super(MACAddressForm, self).__init__(*args, **kwargs)
        self.node = node

    def save(self, *args, **kwargs):
        mac = super(MACAddressForm, self).save(commit=False)
        mac.node = self.node
        if kwargs.get('commit', True):
            mac.save(*args, **kwargs)
        return mac


class SSHKeyForm(ModelForm):
    key = forms.CharField(
        label="Public key",
        widget=forms.Textarea(attrs={'rows': '5', 'cols': '30'}),
        required=True)

    class Meta:
        model = SSHKey

    def __init__(self, user, *args, **kwargs):
        super(SSHKeyForm, self).__init__(*args, **kwargs)
        self.user = user

    def validate_unique(self):
        # This is a trick to work around a problem in Django.
        # See https://code.djangoproject.com/ticket/13091#comment:19 for
        # details.
        # Without this overridden validate_unique the validation error that
        # can occur if this user already has the same key registered would
        # occur when save() would be called.  The error would be an
        # IntegrityError raised when inserting the new key in the database
        # rather than a proper ValidationError raised by 'clean'.

        # Set the instance user.
        self.instance.user = self.user

        # Allow checking against the missing attribute.
        exclude = self._get_validation_exclusions()
        exclude.remove('user')
        try:
            self.instance.validate_unique(exclude=exclude)
        except ValidationError, e:
            # Publish this error as a 'key' error rather than a 'general'
            # error because only the 'key' errors are displayed on the
            # 'add key' form.
            error = e.message_dict.pop('__all__')
            e.message_dict['key'] = error
            self._update_errors(e.message_dict)


class MultipleMACAddressField(forms.MultiValueField):

    def __init__(self, nb_macs=1, *args, **kwargs):
        fields = [MACAddressFormField() for i in range(nb_macs)]
        super(MultipleMACAddressField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if data_list:
            return data_list
        return []


def initialize_node_group(node):
    """If `node` is not in a node group yet, enroll it in the master group."""
    if node.nodegroup_id is None:
        node.nodegroup = NodeGroup.objects.ensure_master()


class WithMACAddressesMixin:
    """A form mixin which dynamically adds a MultipleMACAddressField to the
    list of fields.  This mixin also overrides the 'save' method to persist
    the list of MAC addresses and is intended to be used with a class
    inheriting from NodeForm.
    """

    def __init__(self, *args, **kwargs):
        super(WithMACAddressesMixin, self).__init__(*args, **kwargs)
        self.set_up_mac_addresses_field()

    def set_up_mac_addresses_field(self):
        macs = [mac for mac in self.data.getlist('mac_addresses') if mac]
        self.fields['mac_addresses'] = MultipleMACAddressField(len(macs))
        self.data = self.data.copy()
        self.data['mac_addresses'] = macs

    def is_valid(self):
        valid = super(WithMACAddressesMixin, self).is_valid()
        # If the number of MAC address fields is > 1, provide a unified
        # error message if the validation has failed.
        reformat_mac_address_error = (
            self.errors.get('mac_addresses', None) is not None and
            len(self.data['mac_addresses']) > 1)
        if reformat_mac_address_error:
            self.errors['mac_addresses'] = (
                ['One or more MAC addresses is invalid.'])
        return valid

    def clean_mac_addresses(self):
        data = self.cleaned_data['mac_addresses']
        for mac in data:

src/maasserver/views/prefs.py
# Copyright 2012 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Preferences views."""

from __future__ import (
    absolute_import,
    print_function,
    unicode_literals,
    )

__metaclass__ = type
__all__ = [
    'SSHKeyCreateView',
    'SSHKeyDeleteView',
    'userprefsview',
    ]

from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.shortcuts import (
    get_object_or_404,
    render_to_response,
    )
from django.template import RequestContext
from django.views.generic import CreateView
from maasserver.forms import (
    ProfileForm,
    SSHKeyForm,
    )
from maasserver.models import SSHKey
from maasserver.views import (
    HelpfulDeleteView,
    process_form,
    )


class SSHKeyCreateView(CreateView):

    form_class = SSHKeyForm
    template_name = 'maasserver/prefs_add_sshkey.html'

    def get_form_kwargs(self):
        kwargs = super(SSHKeyCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        messages.info(self.request, "SSH key added.")
        return super(SSHKeyCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('prefs')


class SSHKeyDeleteView(HelpfulDeleteView):

    template_name = 'maasserver/prefs_confirm_delete_sshkey.html'
    context_object_name = 'key'
    model = SSHKey

    def get_object(self):
        keyid = self.kwargs.get('keyid', None)
        key = get_object_or_404(SSHKey, id=keyid)
        if key.user != self.request.user:
            raise PermissionDenied("Can't delete this key.  It's not yours.")
        return key

    def get_next_url(self):
        return reverse('prefs')


def userprefsview(request):
    user = request.user
    # Process the profile update form.
    profile_form, response = process_form(
        request, ProfileForm, reverse('prefs'), 'profile', "Profile updated.",
        {'instance': user})
    if response is not None:
        return response

    # Process the password change form.
    password_form, response = process_form(
        request, PasswordChangeForm, reverse('prefs'), 'password',
        "Password updated.", {'user': user})
    if response is not None:
        return response

    return render_to_response(
        'maasserver/prefs.html',
        {
            'profile_form': profile_form,
            'password_form': password_form,
        },
        context_instance=RequestContext(request))

src/maasserver/templates/maasserver/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="en-us" />
    <link rel="stylesheet" href="{% url "combo-maas" %}?{{ CSS_LIST|join:"&" }}" />
    <title>{% block title %}{% endblock %} | {% include "maasserver/site_title.html" %}</title>
    {% block js-conf %}{% include "maasserver/js-conf.html" %}{% endblock %}
    {% block head %}{% endblock %}
    {% if user.is_authenticated %}
        <script type="text/javascript">
        <!--
        YUI().use('maas.user_panel', function (Y) {
          Y.on('load', function() {
            var panel = Y.maas.user_panel.createUserPanelWidget()
            Y.one('#user-options-link').on('click', Y.maas.user_panel.showUserPanelWidget);
          });
        });
        // -->
        </script>
    {% endif %}
</head>
<body class="{% block layout-modifiers %}{% endblock %}">
  {% block html_includes %}{% endblock %}
  <div class="center-page-wrapper">
    <div class="center-page-content">
      {% if user.is_authenticated %}
        <div class="center-page-wrapper">
          <div id="global-header" class="center-page-content">
            <div id="user-nav">
              <a href="#" id="user-options-link">{{ user.username }}
                <img src="{{ STATIC_URL }}img/down_arrow_light.png" alt="Options arrow" />
              </a>
              <ul id="user-options" class="nav hidden">
                <li><a href="{% url 'prefs' %}">Preferences</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
              </ul>
            </div>
            {% block site-switcher %}
              <a href="{% url 'index' %}" title="Return to dashboard">
                {% include "maasserver/site_title.html" %}
              </a>
            {% endblock %}
            <div class="clear"></div>
          </div>
          <div id="header" class="center-page-content">
              <ul id="right-nav" class="nav">
                {% comment %}
                  <!-- To be enabled when we have search functionality -->
                  <li class="search">
                    {% block header-search %}
                      <form action="{% url 'node-list' %}" method="get" id="header-search">
                        <input type="text" name="query" value="Search nodes" class="search-box" />
                      </form>
                    {% endblock %}
                  </li>
                {% endcomment %}
                {% if user.is_superuser %}
                  {% comment %}
                    <!-- To be enabled when we have search functionality -->
                    <li class="divider"></li>
                  {% endcomment %}
                  <li class="icon {% block nav-active-settings %}{% endblock %}">
                    <a href="{% url 'settings' %}">
                      <img src="{{ STATIC_URL }}img/settings.png" alt="Settings" />
                    </a>
                  </li>
                {% endif %}
              </ul>
              <ul id="main-nav" class="nav">
                <li class="icon large {% block nav-active-index %}{% endblock %}">
                  <a href="{% url 'index' %}">
                    <img src="{{ STATIC_URL }}img/home.png" alt="MAAS home" />
                  </a>
                </li>
                <li class="{% block nav-active-node-list %}{% endblock %}">
                  <a href="{% url 'node-list' %}">Nodes</a>
                </li>
              </ul>
            <div class="clear"></div>
          </div>
        </div>
      {% endif %}
      <div id="body">
        <ul id="flash-messages">
          {% for persistent_error in persistent_errors %}
             <li class="warning">{{ persistent_error }}</li>
          {% endfor %}
          {% if messages %}
            {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}</li>
            {% endfor %}
          {% endif %}
        </ul>
        {% block page-title-block %}
          <h1 id="page-title">{% block page-title %}{% endblock %}</h1>
        {% endblock %}
        <div id="content">
            <div id="sidebar">{% block sidebar %}{% endblock %}</div>
            {% block content %}{% endblock %}
            <div class="clear"></div>
        </div>
      </div>
      <div id="footer">
        <img src="{{ STATIC_URL }}img/ubuntu_logo_footer.png" alt="Ubuntu" />
        {% block footer-copyright %}
          <p>&copy; 2012 Canonical Ltd. Ubuntu and Canonical are registered
          trademarks of Canonical Ltd.
          <a class="space-left-small" href="https://wiki.ubuntu.com/ServerTeam/MAAS/" target="_blank">View Documentation</a></p>
        {% endblock %}
        <div class="clear"></div>
      </div>
    </div>
  </div>
</body>
</html>

src/maasserver/templates/maasserver/enlist_preseed.html
{% extends "maasserver/base.html" %}

{% block nav-active-settings %}active{% endblock %}
{% block title %}Enlistment preseed{% endblock %}
{% block page-title %}Enlistment preseed{% endblock %}

{% block content %}
  <pre>
{{ preseed }}
  </pre>
{% endblock %}

src/maasserver/templates/maasserver/form_field.html
{% load field_type %}
<li class="{{ field.html_name }}{% if field.errors %} error{% endif %}">
  <label for="id_{{ field.html_name }}">
    {% ifequal field|field_type "CheckboxInput" %}
      {{ field }}
    {% endifequal %}
    {{ field.label }}
    {% if field.field.required %}
      <span class="required">(required)</span>
    {% endif %}
  </label>
  {% ifnotequal field|field_type "CheckboxInput" %}
    {{ field }}
  {% endifnotequal %}
  <span class="help">{% if field.help_text %}{{ field.help_text }}{% endif %}</span>
  {% if field.errors %}<span class="errors">{{ field.errors }}</span>{% endif %}
</li>

src/maasserver/templates/maasserver/index.html
{% extends "maasserver/base.html" %}

{% block nav-active-index %}active{% endblock %}
{% block title %}Dashboard{% endblock %}
{% block site-switcher %}{% endblock %}

{% block html_includes %}{% include "maasserver/snippets.html" %}
{% endblock %}

{% block head %}
  <script type="text/javascript"
    src="{% url "combo-raphael" %}?raphael-min.js">
  </script>
  <script type="text/javascript">
  <!--
  YUI().use(
    'maas.enums', 'maas.node_add', 'maas.node','maas.node_views',
    'maas.utils', 'maas.longpoll',
    function (Y) {
    Y.on('load', function() {
      // Create Dashboard view.
      var view = new Y.maas.node_views.NodesDashboard({
          srcNode: '#dashboard',
          summaryNode: '#summary',
          numberNode: '#nodes-number',
          descriptionNode: '#nodes-description',
          reservedNode: '#reserved-nodes',
          retiredNode: '#retired-nodes'});
      view.render();

      Y.one('#addnode').on('click', function(e) {
        e.preventDefault();
        Y.maas.node_add.showAddNodeWidget({targetNode: '#dashboard'});
      });

      // Setup TitleEditWidget.
      var title_widget = new Y.maas.utils.TitleEditWidget(
          {srcNode: '.page-title-form'});
      title_widget.render();

      {% if longpoll_queue and LONGPOLL_PATH %}
      // Start longpoll.
        Y.later(0, Y.maas.longpoll, function() {
          var longpollmanager = Y.maas.longpoll.setupLongPollManager(
            '{{ longpoll_queue }}', '{{ LONGPOLL_PATH }}');
        });
      {% else %}
      // Longoll disabled.
      {% endif %}

    });
  });
  // -->
  </script>
{% endblock %}

{% block page-title-block %}
  {% if user.is_superuser %}
    <form action="" method="" class="page-title-form">
      <input type="text" value="{{ global_options.site_name }} MAAS"
             title="Edit the name of this MAAS" />
    </form>
  {% else %}
    <h1 id="page-title">{% include "maasserver/site_title.html" %}</h1>
  {% endif %}
{% endblock %}

{% block content %}
  <div id="dashboard" class="pad-top">
    <div id="chart" class="block size6"></div>
    <div class="block block size8">
      <div id="summary">
        <h2 id="nodes-number" class="super-size pad-top-large"></h2>
        <p id="nodes-description" class="large"></p>
      </div>
      <p id="reserved-nodes" class="medium space-bottom-small"></p>
      <p id="retired-nodes" class="secondary medium space-top-none"></p>
      <a href="#" id="addnode" class="button right space-top">+ Add node</a>
    </div>
    <div class="clear"></div>
  </div>
{% endblock %}

src/maasserver/templates/maasserver/node_preseed.html
{% extends "maasserver/base.html" %}

{% block nav-active-settings %}active{% endblock %}
{% block title %}Preseed for node: {{ node.hostname }}{% endblock %}
{% block page-title %}Preseed for node: {{ node.hostname }}{% endblock %}
{% block layout-modifiers %}sidebar{% endblock %}

{% block sidebar %}
  <h4>Node details</h4>
  <a href="{% url 'node-view' node.system_id %}" class="button secondary">
    View node
  </a>
{% endblock %}

{% block content %}
  {% if is_commissioning %}
  This node is comissioning.  This is the comissioning preseed.
  {% endif %}
  <pre>
{{ preseed }}
  </pre>
{% endblock %}

src/maasserver/templates/maasserver/prefs_add_sshkey.html
{% extends "maasserver/base.html" %}

{% block title %}Add SSH key{% endblock %}
{% block page-title %}Add SSH key{% endblock %}

{% block content %}
  <form action="." method="post" class="block auto-width">
    {% csrf_token %}
    <ul>
    {% for field in form %}
      {% include "maasserver/form_field.html" %}
    {% endfor %}
    </ul>
    <a class="link-button" href="{% url 'prefs' %}">Cancel</a>
    <input type="submit" class="right" value="+ Add key" />
  </form>
{% endblock %}

src/maasserver/templates/maasserver/prefs_confirm_delete_sshkey.html
{% extends "maasserver/base.html" %}

{% block title %}Delete SSH key{% endblock %}
{% block page-title %}Delete SSH key{% endblock %}

{% block content %}
    <div class="block auto-width">
        <h2>
          Are you sure you want to delete the following key?<br />
        </h2>
        <p style="word-wrap: break-word; width: 700px;">{{ key }}</p>
        <p>This action is permanent and can not be undone.</p>
        <p>
          <form action="." method="post">{% csrf_token %}
            <input type="hidden" name="post" value="yes" />
            <input type="submit" value="Delete key" class="right" />
            <a href="{% url 'prefs' %}">Cancel</a>
          </form>
        </p>
    </div>
{% endblock %}

src/maasserver/templates/maasserver/snippets.html
<script type="text/x-template" id="add-macaddress">
  <p>
    <label for="id_mac_addresses">Mac address</label>
    <input type="text" maxlength="30" name="mac_addresses"
           id="id_mac_addresses" />
    <div class="field-help">e.g AA:BB:CC:DD:EE:FF</div>
  </p>
</script>
<script type="text/x-template" id="add-node">
  <p>
    <label for="id_hostname">Hostname
      <span class="form-optional">(optional)</span>
    </label>
    {{ node_form.hostname }}
    <div class="field-help">Default is MAC-based, e.g. "node-aabbccddeeff"
    </div>
  </p>
  <p>
    <label for="id_after_commissioning_action">After commissioning</label>
    {{ node_form.after_commissioning_action }}
  </p>
  <p>
    <label for="id_architecture">Architecture</label>
    {{ node_form.architecture }}
  </p>
  {% if node_form.power_type %}
    <p>
      <label for="id_power_type">Power type</label>
      {{ node_form.power_type }}
    </p>
    <p class="power_parameters">
      <label for="id_power_parameters">Power parameters</label>
      {{ node_form.power_parameters }}
    </p>
  {% endif %}
</script>
{% for power_type, fieldset in POWER_TYPE_PARAMETERS_FIELDS %}
  <script type="text/x-template" id="power-param-form-{{ power_type}}">
    {{ fieldset }}
  </script>
{% endfor %}
<script type="text/x-template" id="power-param-form-">
</script>